### ISSUE TITLE
Learning Resources Component - Documentation Updates

### ISSUE THREAD

**Issue by owlboy** [oel-mediateam/idstyleguide#24]
We need to have the Resources [example code](https://media.uwex.edu/content/media/documentation/idstyleguide/learning_resources.html) updated to show examples of real content to make it easier to understand all the parts. There are also a few things missing from the example.

###### Missing From the Droplets Example:
* Headers (In my mockup they are "Required" and "Recommended"
* Long title at the top of the notes section.
* Examples of Multiple headers in the notes area.
* Examples of Lists in the notes area.

###### Example Content:
* In context:
    * https://media.uwex.edu/sandbox/bryan/resources_mockup/
* The original Document Terry Sent me:
    * https://docs.google.com/document/d/1xoxdTezIzFfJwzAsOkEMBAMikc988fTW2iEhISK_tBE/edit

**Comment by Lin87** [comment]
long done
