### ISSUE TITLE
Icon requests

### ISSUE THREAD

**Issue by ntewings** [oel-mediateam/idstyleguide#26]
Ethan, 

Can we create 3 new icons?
Welcome
![welcome](https://cloud.githubusercontent.com/assets/13696254/9139119/bd357478-3ced-11e5-9b55-03aadb01f28c.png)
Competency (can you remove the check mark?)
![competency](https://cloud.githubusercontent.com/assets/13696254/9139125/c95a067e-3ced-11e5-8c78-1f5c6d08c166.png)
Tech Needs
![tech needs](https://cloud.githubusercontent.com/assets/13696254/9139135/d6a52840-3ced-11e5-8477-1c39533cd32b.png)
 
Thanks!
-Nate

**Comment by owlboy** [comment]
@ntewings 
Hey nate! 

Can you provide links to where you got these images so we know if we can use them outright, if we have to purchase them, or if we need to make something of our own.

Thanks!

**Comment by ntewings** [comment]
I got Tech needs here- http://fortawesome.github.io/Font-Awesome/icons/

I think I googled the others

-           Nate

**Comment by Lin87** [comment]
It would be even better if you could choose the icons here at https://icomoon.io/#preview-ultimate to meet your need. We have all the icons listed here ready for our use. If you really want to use the icons that you provided and cannot find a similar icon at icomoon, it would require time to made, and I will not be the one to illustrate the icons.

**Comment by ntewings** [comment]
For icon moon I’d recommend
Tech Needs -  “Cogs”

From fotolia the following:

Welcome – File: #65772661
Competencies - File: #63497845 (bottom left image)

-           Nate

**Comment by Lin87** [comment]
@ntewings Is there a date/time you would like to have them by?

**Comment by ntewings** [comment]
I know Stephen would like to use them for Data Science, so is a couple of weeks reasonable?

-           Nate

**Comment by Lin87** [comment]
Yes, in the meantime he or you can start using the followings in your page  
`<span class="icon-tech"></span>`  
`<span class="icon-welcome"></span>`  
`<span class="icon-competency"></span>`

Once the icons are update, they will automatically show up without the need of going back and adding it.

**Comment by ntewings** [comment]
Perfect.

-           Nate

**Comment by Lin87** [comment]
Done! For details, see incoming email.

**Comment by ntewings** [comment]
Thank you!

-           Nate
