### ISSUE TITLE
CSS Inactive Tabs not standing out enough 

### ISSUE THREAD

**Issue by ntewings** [oel-mediateam/idstyleguide#27]
Hello, 

We've heard from a number of end users and faculty that students are at times missing that there are other tabs on a content page, when the tabs style is used.  

Is there someway that we can try to make the inactive tabs standout a bit more as being active?  Perhaps this is something we can do with our existing CSS options or perhaps a new solution/modification to the existing Tab style is needed.

Thoughts?

**Comment by Lin87** [comment]
I'll discuss this with @patrick-wirth , @owlboy , and @mwolfensteinuwex .

**Comment by ntewings** [comment]
Here is an example of something I’ve used.

-           Nate
